name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Linux_x86_64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        check-latest: true

    - name: Install desktop-file-utils
      run: sudo apt-get install -y desktop-file-utils

    - name: Build TV Downloader
      run: python build.py build

    - name: Upload Binary
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./out/*"
        allowUpdates: true
        tag: "continious-build"

  Linux_aarch64:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build in ARM64 Environment
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker build --platform linux/arm64 -t tv-downloader:latest .

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        check-latest: true

    - name: Build TV Downloader
      run: docker run --rm -v $(pwd):/workspace -w /workspace tv-downloader:latest python build.py build

    - name: Upload Binary
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./out/*"
        allowUpdates: true
        tag: "continuous-build"
  
  Windows_x86_64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        check-latest: true
        
    - name: Build TV Downloader
      run: python build.py build

    - name: Upload Binary
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./out/*"
        allowUpdates: true
        tag: "continious-build"