name: Build Binary

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Download Appimagetool
      run: sudo apt-get install -y appimagetool

    - name: Build TV Downloader
      run: make appimage

    - name: Upload Binary
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./out/*"
        allowUpdates: true
        tag: "continious-build"
