name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Linux_x86_64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install desktop-file-utils
      run: sudo apt-get install -y desktop-file-utils

    - name: Build TV Downloader
      run: python build.py build

    - name: Upload Binary
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./out/*"
        allowUpdates: true
        tag: "continious-build"
      
  Linux_aarch64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu_latest

          githubToken: ${{ github.token }}

          shell: /bin/sh

          run: |
            sudo apt-get install -y desktop-file-utils

      - name: Upload Binary
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./out/*"
          allowUpdates: true
          tag: "continious-build"