name: test

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  Linux_arm64:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Install desktop-file-utils
        run: sudo apt-get install -y desktop-file-utils

      - name: Build TV Downloader
        run: python build.py build

      - name: Upload Binary
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./out/*"
          allowUpdates: true
          tag: "continious-build"